const data = {
  products: [
    {
      name: "Free Shirt",
      category: "Shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Classic Shirt",
      category: "Shirts",
      image: "/images/shirt2.jpg",
      price: 70,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      category: "Shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brand: "New Balance",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Free Pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 70,
      brand: "Off White",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Classic Pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 70,
      brand: "Jordan",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
  ],
};
